version: '3'

services:
  backend:
    build: ./server
    ports:
      - '${BACKEND_PORT:-5005}:5000'
    environment:
      - NODE_ENV=$NODE_ENV
    depends_on:
      - db
    restart: always
    volumes:
      - ./server:/app
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - '${FRONTEND_PORT:-3003}:3000'
    depends_on:
      - backend
    restart: always
    volumes:
      - ./client:/app
    networks:
      - app-network

  db:
    image: mongo:6.0.5
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./mongo/data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
